defmodule AdventOfCode2024.Day8Test do
  use ExUnit.Case

  alias AdventOfCode2024.Day8
  alias AdventOfCode2024.Solution

  test "solve/1" do
    input = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............\
    """

    assert %Solution{part1: 14, part2: 34} == Day8.solve(input)
  end
end
